# Generated by Django 5.0.6 on 2024-07-09 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strict_invite', '0002_alter_user_managers_user_created_at_user_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
